[project]
name = "client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "openai>=1.72.0",
    "openai-agents>=0.0.9",
    "socksio>=1.0.0",
]
